name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dataciviclab/.github/actions/python-setup@main
        with:
          extra-packages: -e ".[dev]"
      - name: Test
        run: python3 -m pytest tests/ -v
